server:
  port: 8095
spring:
  application:
    name: admin-service
  rabbitmq:
    host: localhost
    port: 5672
    username: dulich
    password: dulich_secret
  data:
    redis:
      host: localhost
      port: 6379
      password: dulich_secret
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
