server:
  port: 8761

spring:
  application:
    name: eureka-server

# Eureka server configuration
# registerWithEureka: false — this IS the registry, don't register with itself
# fetchRegistry: false — no need to fetch from another Eureka instance
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
